version: '3.3'

services:

  api:
    build: 
      context: .
      dockerfile: flask-tdd-docker/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
      - "80:80"
      - "5004:5000"
    network_mode: bridge
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development